import Head from 'next/head';
import Image from 'next/image';
import InsertionSort from '../components/InsertionSort';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Visualized Sort Algorithm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Visualized Sort Algorithm</h1>

        <p>
          Get started by editing <code>pages/index.js</code>
        </p>
      </main>

      <InsertionSort />
    </div>
  );
}
