import Head from 'next/head';
import Image from 'next/image';
import InsertionSort from '../components/InsertionSort';
import styled from 'styled-components';

const Container = styled.div`
  padding: 10px;
`;
export default function Home() {
  return (
    <Container>
      <Head>
        <title>Visualized Sort Algorithm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Visualized Sort Algorithm</h1>
      </main>

      <InsertionSort />
    </Container>
  );
}
